name: Pages

on:
  push:
    branches:
      - source # default branch

jobs:
  pages:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Install pandoc 2.17.1.1
        uses: pandoc/actions/setup@v1
        with:
          version: 2.17.1.1
      - uses: actions/checkout@v2
      - name: Use Node.js 10.24.1
        uses: actions/setup-node@v2
        with:
          node-version: "10.24.1"
      - name: Cache NPM dependencies
        uses: actions/cache@v2
        with:
          path: node_modules
          key: ${{ runner.OS }}-npm-cache
          restore-keys: |
            ${{ runner.OS }}-npm-cache
      - name: Install Dependencies
        run: npm install
      - name: Build
        run: npm run build
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.gh-pages-github-actions }}
          publish_branch: master
          publish_dir: ./public